import React, {useState, useContext, useEffect} from 'react';
import * as firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/storage';
import {AuthContext} from '../../Auth/AuthContext';
import {CurrentDate} from '../../../utils/CurrentDate';
import {useHistory, useParams} from 'react-router-dom';
import {AlertMessageContext} from '../../../components/common/AlertMessageContext/AlertMessageContext';
import useForm from '../../../hooks/useForm';

export default function AddUpdateOffer() {
    const db = firebase.firestore();
    const history = useHistory();
    const {id} = useParams();

    const {user} = useContext(AuthContext);
    const {setAlertMessage} = useContext(AlertMessageContext);

    const [file, setFile] = useState('');

    const [initialValues, setInitialValues] = useState({
        title: '',
        description: '',
        reviewDate: CurrentDate(),
        imageUrl: '',
    });

    const validationRules = {
        title: [{type: 'required'}],
        description: [{type: 'required'}],
    };

    const [offer, errors, bindInput, isFormValid] = useForm(initialValues, validationRules);

    useEffect(() => {
        if (!id) {
            return;
        }
        // Access collection with name 'offers' then get document with autogenerated id
        const unsub = db
            .collection('offers')
            .doc(id)
            .onSnapshot(res => {
                setInitialValues(res.data());
            });

        return unsub;
    }, [db, id]);

    function handleFileUpload(e) {
        setFile(e.target.files[0]);
        const fr = new FileReader();
        fr.readAsDataURL(e.target.files[0]);
        fr.onload = ({target: {result}}) => setInitialValues({...offer, imageUrl: result});
    }

    async function handleAddoffer() {
        if (!isFormValid()) {
            return;
        }

        if (user && offer.title) {
            let imageUrl = '';
            try {
                if (file) {
                    const imageRef = firebase
                        .storage()
                        .ref()
                        .child(`images/${Math.floor(Math.random() * 10000) + file.name}`);
                    const snapshot = await imageRef.put(file);
                    imageUrl = await snapshot.ref.getDownloadURL();
                }

                await db.collection('offers').add({
                    title: offer.title,
                    description: offer.description,
                    offerDate: CurrentDate(),
                    imageUrl: imageUrl,
                });

                setAlertMessage({
                    message: 'Offer successfully added!',
                    type: 'success',
                });
                history.push('/admin/offers');
            } catch (error) {
                setAlertMessage({
                    message: error.message,
                    type: 'danger',
                });
            }
        }
    }

    async function handleUpdateoffer(item) {
        if (!isFormValid()) {
            return;
        }

        try {
            await db.collection('offers').doc(id).update({
                title: item.title,
                description: item.description,
                imageUrl: item.imageUrl,
                active: true,
            });

            setAlertMessage({
                message: 'Offer successfully updated!',
                type: 'success',
            });
            history.push('/admin/offers');
        } catch (error) {
            setAlertMessage({
                message: error.message,
                type: 'danger',
            });
        }
    }

    return (
        <>
            <form onSubmit={id ? handleUpdateoffer : handleAddoffer}>
                {alert && alert.message ? (
                    <div className={`alert alert-${alert.type}`} role="alert">
                        {alert.message}
                    </div>
                ) : null}
                <div className="jumbotron jumbotron-fluid h-100">
                    <div className="container">
                        <h1 className="display-4">{id ? 'Update Offer' : 'Add Offer'}</h1>
                        <div className="d-flex flex-column form-group pb-3">
                            {offer && offer.imageUrl ? (
                                <img src={offer.imageUrl} width="200" className="rounded shadow" alt="offer" />
                            ) : (
                                ''
                            )}
                            <br />
                            <label>Upload an image:</label>
                            <input className="form-control-file" type="file" onChange={handleFileUpload} />
                        </div>

                        <div className="input-group mb-3">
                            <input
                                type="text"
                                className={`form-control  ${errors.title && 'is-invalid'}`}
                                placeholder="Insert offer title"
                                name="title"
                                value={offer.title}
                                {...bindInput('title')}
                            />
                        </div>

                        <div className="input-group">
                            <textarea
                                type="text"
                                className={`form-control  ${errors.title && 'is-invalid'}`}
                                id="description"
                                name="description"
                                placeholder="Insert offer description"
                                rows="6"
                                value={offer.description}
                                {...bindInput('description')}
                            />
                        </div>
                        <div className="input-group justify-content-center mt-3">
                            <button
                                className="btn btn-primary"
                                disabled={!offer.title}
                                type="button"
                                onClick={id ? () => handleUpdateoffer(offer) : handleAddoffer}
                            >
                                {id ? 'Save' : 'Add'}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </>
    );
}
